### ISSUE TITLE
[codestyle] Mark all functions with a direct throw with KDoc annotations

### ISSUE THREAD

**Issue by junlarsen** [junlarsen/llvm4j#187]
KDoc comments have the option to include a `@throws` tag for any function which may throw an exception. This PR requests any function which has a throw statement inside of it to document the thrown exception with a `@throws` tag.

The functions in question can easily be found through grep'ing `throw`

**Comment by ardlank** [comment]
@supergrecko Can I work on this?

**Comment by ardlank** [comment]
PR: https://github.com/gouri-panda/XPlayer/pull/16

**Comment by junlarsen** [comment]
Sure thing, let me know if you have any further questions.

**Comment by ardlank** [comment]
PR: https://github.com/vexelabs/bitbuilder/pull/191
