### ISSUE TITLE
Remove "cast" constructors

### ISSUE THREAD

**Issue by dhruvrajvanshi** [junlarsen/llvm4j#64]
Right now, there are constructors in most types that take an argument of the same type,

For example,
```kt
class PointerType {
    public constructor(type: Type): this(type.ref)
}
```
This is deeply problematic because of this

```kt

val voidPointer = PointerType(VoidType()) // this is a void instead of void*. Yikes

```

This caused my languages test suites to segfault on generated code. I suggest removing these constructors and do explicit casting using the old way .asSomeType() and so on

**Comment by dhruvrajvanshi** [comment]
I'm working on a PR to remove these constructors.

**Comment by junlarsen** [comment]
That's really strange because the code for it is pretty much the same... Here's the old code for those methods

```kotlin
    public fun asArrayType(): ArrayType = ArrayType(llvmType)
    public fun asFloatType(): FloatType = FloatType(llvmType)
    public fun asFunctionType(): FunctionType = FunctionType(llvmType)
    public fun asIntType(): IntType = IntType(llvmType)
    public fun asPointerType(): PointerType = PointerType(llvmType)
    public fun asStructType(): StructType = StructType(llvmType)
    public fun asVectorType(): VectorType = VectorType(llvmType)
    public fun asVoidType(): VoidType = VoidType(llvmType)
```

**Comment by dhruvrajvanshi** [comment]
I get that the code is the same but the intention was explicit before. When you look at
```PointerType(someType)``` it looks like you're creating a pointer to `someType`. When you look at `someType.asPointerType` it looks more like "I know someType is already a Pointer type so I'm casting it to that". The old code would have segfaulted too but it was harder to call the old one accidentally.

**Comment by junlarsen** [comment]
Yeah, makes sense. I agree that the old approach was easier better.

**Comment by dhruvrajvanshi** [comment]
Other than that, I'm liking the rest of the constructors. Much cleaner than PointerType.new(thingy)
