### ISSUE TITLE
Implement Constant namespace/module

### ISSUE THREAD

**Issue by junlarsen** [junlarsen/llvm4j#74]
While implementing a lot of the Value APIs I have noticed that the values we're working with are constants which have their own APIs which are only available for Constants [(see docs)](https://llvm.org/doxygen/group__LLVMCCoreValueConstant.html)

I have been considering adding a Constant class/namespace which would allow us to add these APIs which are Constant specific.

This way we'd be able to differentiate between constant values (integers, arrays, structs etc) and non-constant values like instructions and users

**Pros**
- Less overhead by not calling `isConstant()`
- Avoids polluting Intellisense for things which wouldn't work
- Able to differentiate from Value and Constant
- Better representation of the IR
- Maps better to the C++ API

**Cons**
- Adds a lot more classes
  - ArrayConstant, IntConstant etc
- Adds more complexity to the library

**Comment by junlarsen** [comment]
Would like to hear what you think about this @dhruvrajvanshi. I think this is the most logical way to do this but just like we discussed in #70 we could probably put it on hold for now

**Comment by dhruvrajvanshi** [comment]
Similar thoughts on this one as well. For anything serious, one would eventually run into this, so it would be a good start to copy what llvm c++ is doing.

**Comment by junlarsen** [comment]
Yeah, that's what I was thinking as well. I think I'm going to refactor a lot of the Values part. I'll mirror the C++ API

**Comment by junlarsen** [comment]
I imagine the folder/library structure for Values should look something like the Doxygen for the C++ Values API, excluding the bits the C API doesn't cover

![image](https://user-images.githubusercontent.com/42585241/78504223-f55de980-776b-11ea-89fa-f3ec62d59bd2.png)

**Comment by junlarsen** [comment]
Solved in #76
